### ISSUE TITLE
Indication of when reverb or EQ are on in tabs

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/audealize-plugin#38]
In the combined version, it would be nice to know if either the EQ or reverb is on just by looking at the tabs. Having a little icon, or color change for the actual tab would be nice. Especially when you first open the app and both reverb and EQ are on (which I don't think they should both be on by default, as it's confusing).

**Comment by michaeldonovan** [comment]
Fixed in v0.2.0-beta -- added effect on/off buttons to the tabs, set effects off by default until a descriptor is selected
